create table IF NOT EXISTS PASSWD (passwd_id bigint generated by default as identity,password varchar(255),salt varchar(255),primary key (passwd_id))
create table IF NOT EXISTS PERSON (id bigint generated by default as identity,firstname varchar(255),lastname varchar(255),email varchar(255),age int,passwd_id bigint ,primary key (id), foreign key (passwd_id) references PASSWD(passwd_id))
